# Generated by Django 2.2.1 on 2019-10-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('page_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
                ('post_creation_date', models.DateTimeField()),
                ('post_url', models.URLField(blank=True)),
            ],
        ),
    ]
