# Generated by Django 2.2.1 on 2019-10-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='Cantus link online')),
                ('cantus_title', models.CharField(max_length=200, verbose_name='Titel')),
                ('cantus_desc', models.TextField(verbose_name='Beschrijving')),
                ('cantus_link', models.URLField(verbose_name='Link')),
                ('cantus_beer_price_m', models.FloatField(verbose_name='Prijs bier lid')),
                ('cantus_beer_price_nm', models.FloatField(verbose_name='Prijs bier niet-lid')),
                ('cantus_water_price_m', models.FloatField(verbose_name='Prijs water lid')),
                ('cantus_water_price_nm', models.FloatField(verbose_name='Prijs water niet-lid')),
                ('cantus_location', models.CharField(max_length=200, verbose_name='Locatie')),
            ],
            options={
                'verbose_name_plural': 'cantusses',
            },
        ),
        migrations.CreateModel(
            name='CantusReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_firstname', models.CharField(max_length=200, verbose_name='Voornaam')),
                ('reg_lastname', models.CharField(max_length=200, verbose_name='Achternaam')),
                ('reg_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('reg_member', models.BooleanField(verbose_name='Lid van LBK')),
                ('reg_drink', models.CharField(choices=[('B', 'Bier'), ('W', 'Water')], max_length=5, verbose_name='Bier/water')),
                ('cantus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cantus')),
            ],
        ),
    ]
