# Generated by Django 2.2.1 on 2019-10-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cantus_cantusreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_text',
        ),
    ]
