# Generated by Django 2.2.1 on 2019-10-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191008_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('pub_date', models.DateTimeField(verbose_name='Event link online')),
                ('event_title', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Titel')),
                ('event_desc', models.TextField(verbose_name='Beschrijving')),
                ('event_link', models.URLField(verbose_name='Link')),
                ('event_price_nm', models.FloatField(verbose_name='Prijs niet-lid')),
                ('event_price_m', models.FloatField(verbose_name='Prijs lid')),
                ('event_location', models.CharField(max_length=200, verbose_name='Locatie')),
            ],
        ),
        migrations.CreateModel(
            name='EventReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_firstname', models.CharField(max_length=200, verbose_name='Voornaam')),
                ('reg_lastname', models.CharField(max_length=200, verbose_name='Achternaam')),
                ('reg_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('reg_member', models.BooleanField(verbose_name='Lid van LBK')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='cantusreg',
            name='cantus',
        ),
        migrations.DeleteModel(
            name='Cantus',
        ),
        migrations.DeleteModel(
            name='CantusReg',
        ),
    ]
