# Generated by Django 2.2.1 on 2019-10-09 00:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191009_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
