# Generated by Django 2.2.1 on 2019-10-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dbmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbmember',
            options={'verbose_name': 'DB member'},
        ),
    ]
