# Generated by Django 2.2.1 on 2019-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191009_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbmember',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='dbmember',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, verbose_name='Gsm-nummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbmember',
            name='profile_picture',
            field=models.ImageField(default=0, upload_to='', verbose_name='Profielfoto'),
            preserve_default=False,
        ),
    ]
