# Generated by Django 2.2.1 on 2019-10-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191009_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmember',
            name='profile_picture',
            field=models.ImageField(upload_to='db_fotos', verbose_name='Profielfoto'),
        ),
    ]
