# Generated by Django 2.2.1 on 2019-10-12 10:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191009_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
