# Generated by Django 2.2.6 on 2020-02-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_page_page_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmember',
            name='profile_picture',
            field=models.ImageField(upload_to='db', verbose_name='Profielfoto'),
        ),
    ]
