# Generated by Django 2.2.6 on 2020-03-10 14:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200214_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_id', models.FloatField()),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, upload_to='')),
                ('vacancy_function', models.CharField(max_length=200)),
                ('vacancy_description', ckeditor.fields.RichTextField()),
                ('vacancy_url', models.URLField()),
            ],
        ),
    ]
