# Generated by Django 2.2.6 on 2020-03-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_vacancies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancies',
            new_name='Vacancy',
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'Vacancies'},
        ),
    ]
