# Generated by Django 2.2.6 on 2020-03-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200310_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy_id',
        ),
    ]
