# Generated by Django 2.2.6 on 2020-04-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200310_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_index',
            field=models.IntegerField(default=0),
        ),
    ]
