# Generated by Django 2.2.6 on 2020-04-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_running'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='running',
            options={'verbose_name': 'Form'},
        ),
    ]
