# Generated by Django 2.2.6 on 2020-04-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200404_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='running',
            name='workgroup',
            field=models.CharField(choices=[('Penning', 'Penning'), ('Communicatie', 'Communidcatie'), ('Gnorgl', 'Gnorgl'), ('Baarr', 'Baarr'), ('Activiteiten', 'Activiteiten'), ('Sport', 'Sport'), ('Cultuur', 'Cultuur'), ('Internationaal', 'Internationaal'), ('Bedrijvenrelaties', 'Bedrijvenrelaties'), ('Onderwijs', 'Onderwijs'), ('Logistiek', 'Logistiek'), ('Cursusdienst', 'Cursusdienst'), ('ICT', 'ICT')], max_length=50, null=True, verbose_name='Werkgroep'),
        ),
    ]
