# Generated by Django 2.2.6 on 2020-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200404_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='running',
            name='q1b',
            field=models.TextField(blank=True, null=True, verbose_name='Verbetering LBK toekomst'),
        ),
        migrations.AddField(
            model_name='running',
            name='q2b',
            field=models.TextField(blank=True, null=True, verbose_name='Samenwerking team'),
        ),
        migrations.AlterField(
            model_name='running',
            name='workgroup',
            field=models.CharField(blank=True, choices=[('Penning', 'Penning'), ('Communicatie', 'Communicatie'), ('Gnorgl', 'Gnorgl'), ('Baarr', 'Baarr'), ('Activiteiten', 'Activiteiten'), ('Sport', 'Sport'), ('Cultuur', 'Cultuur'), ('Internationaal', 'Internationaal'), ('Bedrijvenrelaties', 'Bedrijvenrelaties'), ('Onderwijs', 'Onderwijs'), ('Logistiek', 'Logistiek'), ('Cursusdienst', 'Cursusdienst'), ('ICT', 'ICT')], max_length=50, null=True, verbose_name='Werkgroep'),
        ),
    ]
