# Generated by Django 2.2.6 on 2020-04-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200405_1308'),
        ('main', '0020_page_page_index'),
    ]

    operations = [
    ]
