# Generated by Django 2.2.6 on 2020-04-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_20200412_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_werkgroeplogo',
            field=models.ImageField(default='', upload_to='lbksite/main/static/main/images/werkgroepen/'),
        ),
    ]
