# Generated by Django 2.2.6 on 2020-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_page_page_werkgroeplogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_werkgroeplogo',
            field=models.FilePathField(default='werkgroepen', path='/lbksite/main/static/main/images/werkgroepen'),
        ),
    ]
