# Generated by Django 2.2.6 on 2020-04-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200412_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_werkgroeplogo',
            field=models.ImageField(upload_to='werkgroepen', verbose_name='Icoon'),
        ),
    ]
